#!/bin/bash
set -euo pipefail

# Autor: Leonardo Bruno
# Versão: 4.0
# data: 19/05/2025

echo "Iniciando instalação..."

TEMP_DIR=$(mktemp -d)
NOME_ARQUIVO="gerenciador-python"
URL_DOWNLOAD="https://raw.githubusercontent.com/souza-lb/gerenciador-python/main/gerenciador-python"

echo "Executando download..."
if ! wget --no-verbose --show-progress "$URL_DOWNLOAD" -O "$TEMP_DIR/$NOME_ARQUIVO"; then
    echo "Erro ao baixar o arquivo!"
    rm -rf "$TEMP_DIR"
    exit 1
fi

chmod +x "$TEMP_DIR/$NOME_ARQUIVO"
mkdir -p "$HOME/.bin"
cp "$TEMP_DIR/$NOME_ARQUIVO" "$HOME/.bin/"

if ! grep -q "# CONFIG_GERENCIADOR_AUTO" "$HOME/.bashrc"; then
    {
        echo -e "\n# CONFIG_GERENCIADOR_AUTO"
        echo 'export PATH="$PATH:$HOME/.bin"'
        echo "# ------------------------------"
    } >> "$HOME/.bashrc"
fi

echo "Executando limpeza..."  # Nova mensagem adicionada
rm -rf "$TEMP_DIR"

echo "Instalação concluída!"
echo "Execute: source ~/.bashrc"
