#!/bin/bash
set -euo pipefail

# Autor: Leonardo Bruno
# Versão: 4.0
# data: 19/05/2025

echo "Iniciando instalação..."

TEMP_DIR=$(mktemp -d)
NOME_ARQUIVO="gerenciador-python"
URL_DOWNLOAD="https://raw.githubusercontent.com/souza-lb/gerenciador-python/main/gerenciador-python"

# Verifica se o download foi bem sucedido
if ! wget -q "$URL_DOWNLOAD" -O "$TEMP_DIR/$NOME_ARQUIVO"; then
    echo "Erro ao baixar o arquivo!"
    rm -rf "$TEMP_DIR"
    return 1
fi

chmod +x "$TEMP_DIR/$NOME_ARQUIVO"
mkdir -p "$HOME/.bin"
cp "$TEMP_DIR/$NOME_ARQUIVO" "$HOME/.bin/"

if ! grep -q "# CONFIG_GERENCIADOR_AUTO" "$HOME/.bashrc"; then
    {
        echo -e "\n# CONFIG_GERENCIADOR_AUTO"
        echo 'export PATH="$PATH:$HOME/.bin"'
        echo "# ------------------------------"
    } >> "$HOME/.bashrc"
fi

echo "Instalando dependências para compilação do python..."
sudo apt update && sudo apt install -y \
    build-essential libssl-dev zlib1g-dev \
    libncurses5-dev libncursesw5-dev libreadline-dev \
    libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev \
    libexpat1-dev liblzma-dev tk-dev libffi-dev

rm -rf "$TEMP_DIR"
echo "Instalação concluída!"
echo "Execute: source ~/.bashrc"
